### ISSUE TITLE
Chart list not reset when `object`/ `data` changed

### ISSUE THREAD

**Issue by MarcSkovMadsen** [panel-extensions/panel-graphic-walker#33]
You can see this in action when uploading a file in the reference app

https://github.com/user-attachments/assets/17cc5a49-653f-44ae-a750-596c5aa26190

For my use cases I need this to work as I will combine `duckdb` sql with `panel-graphic-walker`. Users will be executing sql queries and exploring the data. Then executing new sql queries and exploring the new data.

Right now the workaround is to create a new python `GraphicWalker` when you want to display new data.

I've asked in https://github.com/Kanaries/graphic-walker/issues/426 how to do this.

**Comment by philippjfr** [comment]
Fixed
